import Link from "next/link";

import { PasswordResetForm } from "@/components/public/account/password-reset-form";

export default async function ResetPasswordPage({ searchParams }: { searchParams: Promise<{ token?: string | string[] }> }) {
  const { token } = await searchParams;
  const resetToken = typeof token === "string" ? token : "";
  if (!resetToken) return <main className="flex flex-1 items-center justify-center px-4 py-12"><p className="text-public-muted-text">Verify your reset code first. <Link href="/forgot-password" className="font-semibold text-public-primary hover:underline">Start again</Link>.</p></main>;
  return <main className="flex-1 px-4 py-8 sm:px-6 sm:py-12 lg:px-8 lg:py-14"><div className="mx-auto grid w-full max-w-[1240px] gap-6 lg:grid-cols-5 lg:gap-8"><aside className="order-2 hidden rounded-2xl border border-public-border bg-[#fffaf6] px-6 py-8 sm:px-9 lg:order-1 lg:col-span-2 lg:block lg:px-10 lg:py-12"><p className="text-xs font-bold tracking-[0.08em] text-public-primary">APOLOGETICS COMMUNITY</p><div className="mt-4 h-0.5 w-8 bg-public-primary" /><h1 className="mt-7 font-editorial text-4xl font-bold leading-tight text-public-text">Strengthen your knowledge. Renew your purpose.</h1><p className="mt-5 text-base leading-7 text-public-muted-text">Reset your password and continue your journey of learning, reflection, and sharing truth with wisdom.</p></aside><section className="order-1 rounded-2xl border border-public-border bg-public-surface p-6 shadow-[var(--public-shadow)] sm:p-10 lg:order-2 lg:col-span-3 lg:p-12"><div className="mx-auto max-w-xl text-center"><p className="text-xs font-bold tracking-[0.08em] text-public-primary">RESET PASSWORD</p><h1 className="mt-4 font-editorial text-4xl font-bold text-public-text sm:text-5xl">Create a new password</h1><p className="mt-3 text-base leading-7 text-public-muted-text">Please enter and confirm your new password. Make sure it is strong and unique.</p><div className="mt-8 text-left"><PasswordResetForm token={resetToken} /></div><div className="mt-8 flex items-center gap-3 text-sm text-public-muted-text"><span className="h-px flex-1 bg-public-border" /><span>or</span><span className="h-px flex-1 bg-public-border" /></div><Link href="/login" className="mt-7 inline-flex text-sm font-semibold text-public-primary hover:underline">← Back to sign in</Link></div></section></div></main>;
}
