"use client";

import { Bold, Heart, ImageIcon, Italic, List, ListOrdered, LoaderCircle, LockKeyhole, MessageCircle, Pencil, Reply, Smile, Trash2 } from "lucide-react";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { createContentCommentAction, deleteOwnContentCommentAction, editContentCommentAction, loadContentCommentRepliesAction, loadMoreContentCommentsAction, reportContentCommentAction, toggleContentCommentLikeAction } from "@/app/(public)/content-comment-actions";
import { MemberAvatar } from "@/components/public/authenticated-member-menu";
import type { ContentType } from "@/generated/prisma/enums";
import type { PublicContentComment } from "@/services/content-comment.service";

type Props = { contentType: ContentType; contentId: string; comments: PublicContentComment[]; nextCursor: string | null; totalCount: number };
type Sort = "newest" | "oldest";

function merge(current: PublicContentComment[], incoming: PublicContentComment[]) {
  return [...new Map([...current, ...incoming].map((comment) => [comment.id, comment])).values()];
}

function Composer({ contentType, contentId, parentId, onComplete, disabled, member, compact = false }: { contentType: ContentType; contentId: string; parentId?: string; onComplete: (comment: PublicContentComment) => void; disabled?: boolean; member?: { name: string; image?: string | null }; compact?: boolean }) {
  const [body, setBody] = useState("");
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string>();
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setError(undefined);
    const result = await createContentCommentAction({ contentType, contentId, parentId, body });
    setPending(false);
    if (!result.ok) return setError(result.message);
    setBody(""); onComplete(result.comment);
  }
  if (compact) return <form onSubmit={submit} className="mt-3"><textarea value={body} onChange={(event) => setBody(event.target.value)} disabled={pending} required maxLength={2000} placeholder="Write a reply..." className="min-h-20 w-full rounded-lg border border-public-border bg-public-surface px-3 py-2 text-sm outline-none focus:border-public-primary focus:ring-2 focus:ring-public-primary/15" /><div className="mt-2 flex items-center gap-3"><button disabled={pending || !body.trim()} className="rounded-lg bg-public-primary px-4 py-2 text-sm font-bold text-white disabled:opacity-55">{pending ? "Posting..." : "Post reply"}</button><button type="button" onClick={() => setBody("")} className="text-sm text-public-muted-text">Clear</button></div>{error ? <p role="alert" className="mt-2 text-sm text-red-700">{error}</p> : null}</form>;
  const tools = [{ label: "Bold", icon: Bold }, { label: "Italic", icon: Italic }, { label: "Bulleted list", icon: List }, { label: "Numbered list", icon: ListOrdered }, { label: "Emoji", icon: Smile }];
  return <form onSubmit={submit} className="mt-5 rounded-xl border border-public-primary/25 bg-public-primary-soft/25 p-3 sm:p-4"><div className="flex gap-3"><MemberAvatar name={member?.name ?? "Guest"} image={member?.image} className="hidden size-12 shrink-0 text-lg sm:flex" /><div className="min-w-0 flex-1 overflow-hidden rounded-lg border border-public-border bg-public-surface"><textarea value={body} onChange={(event) => setBody(event.target.value)} disabled={disabled || pending} required maxLength={2000} aria-label="Comment" placeholder={disabled ? "Sign in to write a comment..." : "Write a comment..."} className="min-h-24 w-full resize-y bg-transparent px-4 py-3 text-sm outline-none placeholder:text-public-muted-text sm:text-base" /><div className="flex min-h-12 flex-wrap items-center gap-1 border-t border-public-border px-2 py-2"><div className="flex">{tools.map(({ label, icon: Icon }) => <button key={label} type="button" disabled title={`${label} formatting is not available for plain-text comments`} className="inline-flex size-8 items-center justify-center text-public-muted-text opacity-50"><Icon className="size-4" /></button>)}</div><button type="button" disabled title="Image attachments are not available for comments" className="ml-auto inline-flex size-8 items-center justify-center text-public-muted-text opacity-50"><ImageIcon className="size-5" /></button><span className="h-6 w-px bg-public-border" /><button disabled={disabled || pending || !body.trim()} className="min-h-9 rounded-lg bg-public-primary px-4 text-sm font-bold text-white disabled:opacity-55">{pending ? <LoaderCircle className="size-4 animate-spin" /> : "Post Comment"}</button></div></div></div>{disabled ? <p className="mt-3 flex items-center gap-2 text-sm text-public-muted-text"><LockKeyhole className="size-4" /><Link href="/login" className="font-semibold text-public-primary hover:underline">Sign in</Link> to comment.</p> : null}{error ? <p role="alert" className="mt-3 text-sm text-red-700">{error}</p> : null}</form>;
}

function CommentTools({ comment, onReply, onEdit, onDelete }: { comment: PublicContentComment; onReply: () => void; onEdit: () => void; onDelete: () => void }) {
  const { status } = useSession(); const router = useRouter(); const [liked, setLiked] = useState(comment.liked); const [likeCount, setLikeCount] = useState(comment.likeCount); const [reportOpen, setReportOpen] = useState(false); const [reason, setReason] = useState("SPAM"); const [message, setMessage] = useState<string>(); const [pending, setPending] = useState(false);
  const signIn = () => router.push(`/login?callbackUrl=${encodeURIComponent(`${window.location.pathname}${window.location.search}`)}`);
  async function toggleLike() { if (status !== "authenticated") return signIn(); setPending(true); const result = await toggleContentCommentLikeAction(comment.id); setPending(false); if (!result.ok) return setMessage(result.message); setLiked(result.summary.liked); setLikeCount(result.summary.count); }
  async function report() { if (status !== "authenticated") return signIn(); setPending(true); const result = await reportContentCommentAction({ commentId: comment.id, reason }); setPending(false); if (!result.ok) return setMessage(result.message); setReportOpen(false); setMessage("Thank you. Your report has been submitted for review."); }
  return <><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-sm"><button onClick={toggleLike} disabled={pending} aria-pressed={liked} className="inline-flex items-center gap-1 font-semibold text-public-primary hover:underline"><Heart className={`size-3.5 ${liked ? "fill-current" : ""}`} />{liked ? "Unlike" : "Like"} ({likeCount})</button><button onClick={onReply} className="inline-flex items-center gap-1 font-semibold text-public-primary hover:underline"><Reply className="size-3.5" />Reply</button><button onClick={() => status === "authenticated" ? setReportOpen(true) : signIn()} className="text-public-muted-text hover:text-public-text">Report</button>{comment.isOwner ? <><button onClick={onEdit} className="inline-flex items-center gap-1 text-public-muted-text hover:text-public-text"><Pencil className="size-3.5" />Edit</button><button onClick={onDelete} className="inline-flex items-center gap-1 text-public-muted-text hover:text-public-text"><Trash2 className="size-3.5" />Delete</button></> : null}</div>{message ? <p role="status" className="mt-2 text-sm text-public-muted-text">{message}</p> : null}{reportOpen ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4" role="presentation"><div role="dialog" aria-modal="true" aria-labelledby={`report-${comment.id}`} className="w-full max-w-sm rounded-xl bg-public-surface p-5 shadow-xl"><h3 id={`report-${comment.id}`} className="font-editorial text-xl font-bold text-public-text">Report comment</h3><label className="mt-4 block text-sm font-semibold text-public-text">Reason<select value={reason} onChange={(event) => setReason(event.target.value)} className="mt-1 w-full rounded-lg border border-public-border bg-public-surface p-2 text-sm"><option value="SPAM">Spam</option><option value="HARASSMENT">Harassment or abuse</option><option value="HATEFUL_CONTENT">Hate or harmful content</option><option value="MISINFORMATION">Misinformation</option><option value="OFF_TOPIC">Off-topic</option><option value="OTHER">Other</option></select></label><div className="mt-5 flex justify-end gap-3"><button onClick={() => setReportOpen(false)} className="text-sm text-public-muted-text">Cancel</button><button onClick={report} disabled={pending} className="rounded-lg bg-public-primary px-4 py-2 text-sm font-bold text-white">Submit report</button></div></div></div> : null}</>;
}

function Comment({ comment, contentType, contentId, depth, refresh }: { comment: PublicContentComment; contentType: ContentType; contentId: string; depth: number; refresh: () => void }) {
  const [replying, setReplying] = useState(false); const [editing, setEditing] = useState(false); const [body, setBody] = useState(comment.body); const [replies, setReplies] = useState<PublicContentComment[]>([]); const [replyCursor, setReplyCursor] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState<string>();
  const published = comment.status === "PUBLISHED";
  async function loadReplies() { setLoading(true); const result = await loadContentCommentRepliesAction({ contentType, contentId, parentId: comment.id, cursor: replyCursor ?? undefined }); setLoading(false); if (!result.ok) return setError(result.message); setReplies((current) => merge(current, result.page.comments)); setReplyCursor(result.page.nextCursor); }
  async function save() { setPending(true); const result = await editContentCommentAction({ commentId: comment.id, body }); setPending(false); if (!result.ok) return setError(result.message); setEditing(false); refresh(); }
  async function remove() { if (!window.confirm("Delete this comment? This cannot be undone.")) return; setPending(true); const result = await deleteOwnContentCommentAction(comment.id); setPending(false); if (!result.ok) return setError(result.message); refresh(); }
  const date = new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(comment.createdAt));
  return <li className={depth ? "mt-4 border-l-2 border-public-border pl-4 sm:ml-6" : "mt-5"}><article className="flex gap-3"><MemberAvatar name={comment.author.name} image={comment.author.image} className="size-10 shrink-0 text-sm" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline gap-x-3 gap-y-1"><h3 className="font-editorial font-bold text-public-text">{published ? comment.author.name : "Comment unavailable"}</h3><time className="text-xs text-public-muted-text" dateTime={new Date(comment.createdAt).toISOString()}>{date}</time></div>{editing ? <div className="mt-2"><textarea value={body} onChange={(event) => setBody(event.target.value)} className="min-h-20 w-full rounded-lg border border-public-border px-3 py-2 text-sm" /><div className="mt-2 flex gap-3"><button onClick={save} disabled={pending} className="text-sm font-bold text-public-primary">Save</button><button onClick={() => { setEditing(false); setBody(comment.body); }} className="text-sm text-public-muted-text">Cancel</button></div></div> : <p className="mt-1 break-words whitespace-pre-wrap text-sm leading-6 text-public-text">{published ? comment.body : "This comment was deleted."}</p>}{published && !editing ? <CommentTools comment={comment} onReply={() => setReplying((value) => !value)} onEdit={() => setEditing(true)} onDelete={remove} /> : null}{error ? <p role="alert" className="mt-2 text-sm text-red-700">{error}</p> : null}{replying ? <Composer compact contentType={contentType} contentId={contentId} parentId={comment.id} onComplete={(reply) => { setReplies((current) => merge(current, [reply])); setReplying(false); }} /> : null}</div></article>{comment.replyCount > replies.length ? <button onClick={loadReplies} disabled={loading} className="mt-3 ml-12 text-sm font-semibold text-public-primary hover:underline">{loading ? "Loading replies..." : replies.length ? "Load more replies" : `View ${comment.replyCount} ${comment.replyCount === 1 ? "reply" : "replies"}`}</button> : null}{replies.length ? <ul>{replies.map((reply) => <Comment key={reply.id} comment={reply} contentType={contentType} contentId={contentId} depth={depth + 1} refresh={refresh} />)}</ul> : null}</li>;
}

export function PublicContentComments({ contentType, contentId, comments: initialComments, nextCursor: initialCursor, totalCount: initialTotalCount }: Props) {
  const { data: session, status } = useSession(); const router = useRouter(); const [comments, setComments] = useState(initialComments); const [cursor, setCursor] = useState(initialCursor); const [totalCount, setTotalCount] = useState(initialTotalCount); const [sort, setSort] = useState<Sort>("newest"); const [loading, setLoading] = useState(false); const [error, setError] = useState<string>();
  const signedIn = status === "authenticated" && session.user?.role === "USER";
  async function fetchPage(nextSort: Sort, nextCursor?: string) { setLoading(true); setError(undefined); const result = await loadMoreContentCommentsAction({ contentType, contentId, sort: nextSort, cursor: nextCursor }); setLoading(false); if (!result.ok) return setError(result.message); setComments((current) => nextCursor ? merge(current, result.page.comments) : result.page.comments); setCursor(result.page.nextCursor); setTotalCount(result.page.totalCount); }
  return <section id="comments" className="mt-10 scroll-mt-24 border-t border-public-border pt-7" aria-labelledby="comments-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="flex items-center gap-2"><MessageCircle className="size-6 text-public-primary" /><h2 id="comments-title" className="font-editorial text-2xl font-bold text-public-text sm:text-3xl">Comments ({totalCount})</h2></div><p className="mt-2 text-sm text-public-muted-text sm:text-base">Join the conversation and share your thoughts.</p></div><label className="text-sm text-public-muted-text">Sort by: <select value={sort} onChange={(event) => { const value = event.target.value as Sort; setSort(value); void fetchPage(value); }} className="bg-transparent font-semibold text-public-primary outline-none"><option value="newest">Newest</option><option value="oldest">Oldest</option></select></label></div><Composer contentType={contentType} contentId={contentId} disabled={!signedIn} member={{ name: session?.user?.name ?? "Guest", image: session?.user?.image }} onComplete={(comment) => { setComments((current) => sort === "newest" ? [comment, ...current] : [...current, comment]); setTotalCount((count) => count + 1); }} />{comments.length ? <ul className="mt-5 divide-y divide-public-border">{comments.map((comment) => <Comment key={comment.id} comment={comment} contentType={contentType} contentId={contentId} depth={0} refresh={() => router.refresh()} />)}</ul> : <p className="mt-5 text-sm text-public-muted-text">Be the first to comment.</p>}{cursor ? <button onClick={() => void fetchPage(sort, cursor)} disabled={loading} className="mt-6 text-sm font-semibold text-public-primary hover:underline">{loading ? "Loading comments..." : "Load more comments"}</button> : null}{error ? <p role="alert" className="mt-3 text-sm text-red-700">{error}</p> : null}</section>;
}
