"use client";

import { MessageCircle, Pencil, Reply, Trash2 } from "lucide-react";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { createContentCommentAction, deleteOwnContentCommentAction, editContentCommentAction, loadContentCommentRepliesAction, loadMoreContentCommentsAction } from "@/app/(public)/content-comment-actions";
import type { ContentType } from "@/generated/prisma/enums";
import type { PublicContentComment } from "@/services/content-comment.service";

type PublicContentCommentsProps = { contentType: ContentType; contentId: string; comments: PublicContentComment[]; nextCursor: string | null; totalCount: number };

function mergeComments(current: PublicContentComment[], incoming: PublicContentComment[]) {
  const byId = new Map(current.map((comment) => [comment.id, comment]));
  for (const comment of incoming) byId.set(comment.id, comment);
  return [...byId.values()];
}

function CommentComposer({ contentType, contentId, parentId, onComplete, placeholder }: { contentType: ContentType; contentId: string; parentId?: string; onComplete: (comment: PublicContentComment) => void; placeholder: string }) {
  const [body, setBody] = useState(""); const [error, setError] = useState<string>(); const [pending, setPending] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(undefined); const result = await createContentCommentAction({ contentType, contentId, parentId, body }); setPending(false); if (!result.ok) { setError(result.message); return; } setBody(""); onComplete(result.comment); }
  return <form onSubmit={submit} className="mt-3 space-y-2"><textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder={placeholder} maxLength={2000} required className="min-h-24 w-full rounded-[var(--public-radius)] border border-public-border bg-public-surface px-3 py-2 text-sm text-public-text outline-none focus:border-public-primary focus:ring-2 focus:ring-public-primary/20" />{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}<button type="submit" disabled={pending} className="inline-flex min-h-9 items-center rounded-[var(--public-radius)] bg-public-primary px-4 text-sm font-bold text-white hover:bg-public-primary-hover disabled:opacity-60">{pending ? "Posting..." : "Post comment"}</button></form>;
}

function CommentNode({ comment, contentType, contentId, depth, refresh }: { comment: PublicContentComment; contentType: ContentType; contentId: string; depth: number; refresh: () => void }) {
  const [replying, setReplying] = useState(false); const [editing, setEditing] = useState(false); const [body, setBody] = useState(comment.body); const [error, setError] = useState<string>(); const [pending, setPending] = useState(false); const [replies, setReplies] = useState<PublicContentComment[]>([]); const [replyCount, setReplyCount] = useState(comment.replyCount); const [replyCursor, setReplyCursor] = useState<string | null>(null); const [loadingReplies, setLoadingReplies] = useState(false);
  const published = comment.status === "PUBLISHED";
  async function saveEdit() { setPending(true); const result = await editContentCommentAction({ commentId: comment.id, body }); setPending(false); if (!result.ok) { setError(result.message); return; } setEditing(false); refresh(); }
  async function remove() { setPending(true); const result = await deleteOwnContentCommentAction(comment.id); setPending(false); if (!result.ok) { setError(result.message); return; } refresh(); }
  async function loadReplies() { setLoadingReplies(true); setError(undefined); const result = await loadContentCommentRepliesAction({ contentType, contentId, parentId: comment.id, cursor: replyCursor ?? undefined }); setLoadingReplies(false); if (!result.ok) { setError(result.message); return; } setReplies((current) => mergeComments(current, result.page.comments)); setReplyCursor(result.page.nextCursor); }
  const placeholder = comment.status === "HIDDEN" ? "This comment has been hidden by a moderator." : "This comment has been deleted.";
  const canLoadReplies = replyCount > replies.length;
  return <li className="mt-4" style={{ marginLeft: `${Math.min(depth, 4) * 0.75}rem` }}><article className="rounded-[var(--public-radius)] border border-public-border bg-public-surface p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold text-public-text">{published ? comment.author.name : "Comment unavailable"}</p><time className="text-xs text-public-muted-text" dateTime={comment.createdAt.toISOString()}>{new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(comment.createdAt))}</time></div>{published && editing ? <div className="mt-3 space-y-2"><textarea value={body} onChange={(event) => setBody(event.target.value)} maxLength={2000} className="min-h-24 w-full rounded-[var(--public-radius)] border border-public-border px-3 py-2 text-sm" /><div className="flex gap-3"><button type="button" onClick={saveEdit} disabled={pending} className="text-sm font-bold text-public-primary">Save</button><button type="button" onClick={() => { setEditing(false); setBody(comment.body); }} className="text-sm font-semibold text-public-muted-text">Cancel</button></div></div> : <p className={published ? "mt-2 whitespace-pre-wrap text-sm leading-6 text-public-muted-text" : "mt-2 text-sm italic text-public-muted-text"}>{published ? comment.body : placeholder}</p>}{error ? <p role="alert" className="mt-2 text-sm text-red-700">{error}</p> : null}{published ? <div className="mt-3 flex flex-wrap gap-3"><button type="button" onClick={() => setReplying((value) => !value)} className="inline-flex items-center gap-1 text-sm font-semibold text-public-primary"><Reply className="size-4" aria-hidden="true" />Reply</button>{comment.isOwner ? <><button type="button" onClick={() => setEditing(true)} className="inline-flex items-center gap-1 text-sm font-semibold text-public-muted-text"><Pencil className="size-4" aria-hidden="true" />Edit</button><button type="button" onClick={remove} disabled={pending} className="inline-flex items-center gap-1 text-sm font-semibold text-public-muted-text"><Trash2 className="size-4" aria-hidden="true" />Delete</button></> : null}</div> : null}{replying && published ? <CommentComposer contentType={contentType} contentId={contentId} parentId={comment.id} placeholder="Write a reply..." onComplete={(createdReply) => { setReplies((current) => mergeComments(current, [createdReply])); setReplyCount((current) => current + 1); setReplying(false); }} /> : null}</article>{canLoadReplies ? <button type="button" onClick={loadReplies} disabled={loadingReplies} className="mt-3 text-sm font-semibold text-public-primary hover:underline">{loadingReplies ? "Loading replies..." : replies.length ? "Load more replies" : `View ${replyCount} ${replyCount === 1 ? "reply" : "replies"}`}</button> : null}{replies.length ? <ul>{replies.map((reply) => <CommentNode key={reply.id} comment={reply} contentType={contentType} contentId={contentId} depth={depth + 1} refresh={refresh} />)}</ul> : null}</li>;
}

export function PublicContentComments({ contentType, contentId, comments: initialComments, nextCursor: initialCursor, totalCount: initialTotalCount }: PublicContentCommentsProps) {
  const { data: session, status } = useSession(); const router = useRouter(); const [comments, setComments] = useState(initialComments); const [totalCount, setTotalCount] = useState(initialTotalCount); const [cursor, setCursor] = useState(initialCursor); const [loadingMore, setLoadingMore] = useState(false); const [error, setError] = useState<string>();
  const isPublicUser = status === "authenticated" && session.user?.role === "USER"; const refresh = () => router.refresh();
  async function loadMore() { if (!cursor) return; setLoadingMore(true); setError(undefined); const result = await loadMoreContentCommentsAction({ contentType, contentId, cursor }); setLoadingMore(false); if (!result.ok) { setError(result.message); return; } setComments((current) => mergeComments(current, result.page.comments)); setCursor(result.page.nextCursor); }
  return <section id="comments" className="mt-10 scroll-mt-24 border-t border-public-border pt-7" aria-labelledby="comments-title"><div className="flex items-center gap-2"><MessageCircle className="size-5 text-public-primary" aria-hidden="true" /><h2 id="comments-title" className="font-editorial text-2xl font-bold text-public-text">Comments ({totalCount})</h2></div>{isPublicUser ? <CommentComposer contentType={contentType} contentId={contentId} placeholder="Share your thoughts..." onComplete={(createdComment) => { setComments((current) => mergeComments(current, [createdComment])); setTotalCount((current) => current + 1); }} /> : <p className="mt-4 text-sm text-public-muted-text"><Link href="/login" className="font-semibold text-public-primary hover:underline">Sign in</Link> to join the conversation.</p>}{comments.length ? <ul className="mt-5">{comments.map((comment) => <CommentNode key={comment.id} comment={comment} contentType={contentType} contentId={contentId} depth={0} refresh={refresh} />)}</ul> : <p className="mt-5 text-sm text-public-muted-text">Be the first to comment.</p>}{cursor ? <button type="button" onClick={loadMore} disabled={loadingMore} className="mt-5 text-sm font-semibold text-public-primary hover:underline disabled:opacity-60">{loadingMore ? "Loading comments..." : "Load more comments"}</button> : null}{error ? <p role="alert" className="mt-3 text-sm text-red-700">{error}</p> : null}</section>;
}
