"use client";

import { CheckCircle2, CircleAlert, Sparkles } from "lucide-react";
import { useState } from "react";

import { EmailVerificationForm, type VerificationFeedback } from "@/components/public/account/email-verification-form";

export function EmailVerificationExperience({ email }: { email: string }) {
  const [feedback, setFeedback] = useState<VerificationFeedback | null>(null);

  return <>{feedback ? <aside className="order-1 lg:order-2 lg:col-span-3 lg:col-start-3 xl:col-span-1 xl:col-start-3 xl:row-start-1 xl:self-center" aria-live="polite"><div className={feedback.kind === "success" ? "rounded-[var(--public-radius)] border border-green-300 bg-green-50 p-4 text-green-950" : "rounded-[var(--public-radius)] border border-red-300 bg-red-50 p-4 text-red-950"}><div className="flex items-start gap-3">{feedback.kind === "success" ? <CheckCircle2 className="mt-0.5 size-5 shrink-0 text-green-700" aria-hidden="true" /> : <CircleAlert className="mt-0.5 size-5 shrink-0 text-red-700" aria-hidden="true" />}<div><h2 className="font-editorial text-base font-bold">{feedback.title}</h2><p className="mt-1 text-sm leading-6">{feedback.message}</p>{feedback.kind === "success" ? <p className="mt-2 text-sm">Redirecting...</p> : null}</div></div></div></aside> : null}<section className="order-2 overflow-hidden rounded-2xl border border-public-border bg-public-surface p-6 shadow-[var(--public-shadow)] sm:p-10 lg:order-3 lg:col-span-3 lg:col-start-3 xl:col-span-1 xl:col-start-2 xl:row-start-1 lg:p-12"><div className="mx-auto max-w-lg text-center"><div className="relative mx-auto flex h-[7.5rem] max-w-[18rem] items-center justify-center"><Sparkles className="absolute left-2 size-6 text-[#c79538]" aria-hidden="true" /><div className="flex size-[4.5rem] items-center justify-center rounded-full border border-public-primary/15 bg-public-primary-soft text-public-primary"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="size-8" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m3 7 9 6 9-6" /></svg></div><Sparkles className="absolute right-2 size-6 text-[#c79538]" aria-hidden="true" /></div><p className="text-sm font-bold tracking-[0.08em] text-public-primary">VERIFY EMAIL</p><h1 className="mt-4 font-editorial text-4xl font-bold tracking-tight text-public-text sm:text-5xl">Confirm your email</h1><p className="mt-3 text-base leading-7 text-public-muted-text">We sent a four-digit verification code to<br /><strong className="font-bold text-public-text">{email}</strong></p><p className="mt-4 text-sm leading-6 text-public-muted-text">Enter the code below to verify your email address.</p><div className="mt-8"><EmailVerificationForm email={email} onFeedbackChange={setFeedback} /></div></div></section></>;
}
