"use client";

import { CircleAlert, CircleCheck, Eye, EyeOff, LockKeyhole } from "lucide-react";
import Link from "next/link";
import { useActionState, useState } from "react";

import { resendPasswordResetCodeAction, resetPasswordAction } from "@/app/(public)/account-actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { initialPublicAccountActionState } from "@/lib/public-account-action-state";

export function PasswordResetForm({ email }: { email: string }) {
  const [state, action, pending] = useActionState(resetPasswordAction, initialPublicAccountActionState);
  const [resendState, resendAction, resendPending] = useActionState(resendPasswordResetCodeAction, initialPublicAccountActionState);
  const [visible, setVisible] = useState(false);
  const [confirmVisible, setConfirmVisible] = useState(false);
  const complete = state.status === "success";
  return <div className="space-y-5"><form action={action} className="space-y-5" noValidate><input type="hidden" name="email" value={email} />{state.status !== "idle" ? <StatusMessage error={state.status === "error"} message={state.message} /> : null}<div className="space-y-2"><label htmlFor="code" className="text-sm font-bold text-public-text">Four-digit reset code</label><Input id="code" name="code" inputMode="numeric" autoComplete="one-time-code" maxLength={4} pattern="[0-9]{4}" required disabled={complete} className="h-[3.25rem] border-public-border bg-public-surface text-center font-editorial text-xl tracking-[0.4em] shadow-none focus-visible:border-public-primary focus-visible:ring-public-primary/20" /></div><PasswordInput id="password" name="password" label="New password" visible={visible} setVisible={setVisible} disabled={complete} /><PasswordInput id="confirm-password" name="confirmPassword" label="Confirm new password" visible={confirmVisible} setVisible={setConfirmVisible} disabled={complete} /><p className="text-xs text-public-muted-text">Use at least 12 characters with uppercase, lowercase, and a number.</p>{complete ? <Link href="/login" className="inline-flex h-[3.25rem] w-full items-center justify-center rounded-[var(--public-radius)] bg-public-primary text-base font-bold text-white hover:bg-public-primary-hover">Sign in</Link> : <Button type="submit" disabled={pending} className="h-[3.25rem] w-full rounded-[var(--public-radius)] bg-public-primary text-base font-bold text-white hover:bg-public-primary-hover">{pending ? "Resetting password..." : "Reset password"}</Button>}</form><form action={resendAction} className="text-center"><input type="hidden" name="email" value={email} />{resendState.status !== "idle" ? <StatusMessage error={resendState.status === "error"} message={resendState.message} /> : null}<Button type="submit" variant="link" disabled={resendPending || complete} className="mt-2 text-public-primary">{resendPending ? "Sending code..." : "Resend code"}</Button></form></div>;
}

function StatusMessage({ error, message }: { error: boolean; message?: string }) { return <p role={error ? "alert" : "status"} className={error ? "flex gap-2 rounded-[var(--public-radius)] border border-red-200 bg-red-50 px-3 py-3 text-sm text-red-800" : "flex gap-2 rounded-[var(--public-radius)] border border-green-200 bg-green-50 px-3 py-3 text-sm text-green-800"}>{error ? <CircleAlert className="size-5 shrink-0" aria-hidden="true" /> : <CircleCheck className="size-5 shrink-0" aria-hidden="true" />}{message}</p>; }

function PasswordInput({ id, name, label, visible, setVisible, disabled }: { id: string; name: string; label: string; visible: boolean; setVisible: (visible: boolean) => void; disabled: boolean }) { return <div className="space-y-2"><label htmlFor={id} className="text-sm font-bold text-public-text">{label}</label><div className="relative"><LockKeyhole className="pointer-events-none absolute left-3 top-[1.125rem] size-5 text-public-muted-text" aria-hidden="true" /><Input id={id} name={name} type={visible ? "text" : "password"} autoComplete="new-password" required disabled={disabled} className="h-[3.25rem] border-public-border bg-public-surface px-11 text-base shadow-none focus-visible:border-public-primary focus-visible:ring-public-primary/20" /><button type="button" onClick={() => setVisible(!visible)} disabled={disabled} className="absolute right-2 top-2 inline-flex size-9 items-center justify-center rounded-sm text-public-muted-text hover:bg-public-primary-soft hover:text-public-primary" aria-label={`${visible ? "Hide" : "Show"} ${label.toLowerCase()}`}>{visible ? <EyeOff className="size-5" aria-hidden="true" /> : <Eye className="size-5" aria-hidden="true" />}</button></div></div>; }
