import { ArrowLeft, BookOpenCheck, MessageCircle, ShieldCheck } from "lucide-react";
import Link from "next/link";

import { PasswordResetRequestForm } from "@/components/public/account/password-reset-request-form";

const benefits = [{ icon: BookOpenCheck, text: "Authentic articles and resources" }, { icon: MessageCircle, text: "Engage in meaningful discussions" }, { icon: ShieldCheck, text: "A safe and respectful community" }];

export default function ForgotPasswordPage() {
  return <main className="flex-1 px-4 py-8 sm:px-6 sm:py-12 lg:px-8 lg:py-14"><div className="mx-auto grid w-full max-w-[1240px] gap-6 lg:grid-cols-5 lg:gap-8"><aside className="order-2 rounded-2xl border border-public-border bg-[#fffaf6] px-6 py-8 sm:px-9 lg:order-1 lg:col-span-2 lg:px-10 lg:py-12"><p className="text-xs font-bold tracking-[0.08em] text-public-primary">APOLOGETICS COMMUNITY</p><div className="mt-4 h-0.5 w-8 bg-public-primary" /><h1 className="mt-7 font-editorial text-4xl font-bold leading-tight text-public-text">Knowledge begins with a sincere seek.</h1><p className="mt-5 text-base leading-7 text-public-muted-text">Reset your password to regain access to your account and continue your journey of learning and sharing beneficial knowledge.</p><ul className="mt-8 grid gap-4 text-sm font-medium text-public-text">{benefits.map(({ icon: Icon, text }) => <li key={text} className="flex items-center gap-3"><Icon className="size-5 text-public-primary" aria-hidden="true" />{text}</li>)}</ul></aside><section className="order-1 rounded-2xl border border-public-border bg-public-surface p-6 shadow-[var(--public-shadow)] sm:p-10 lg:order-2 lg:col-span-3 lg:p-12"><div className="mx-auto max-w-xl text-center"><p className="text-xs font-bold tracking-[0.08em] text-public-primary">RESET YOUR PASSWORD</p><h2 className="mt-4 font-editorial text-4xl font-bold text-public-text sm:text-5xl">Forgot password?</h2><p className="mt-4 text-base leading-7 text-public-muted-text">Enter your email address and we&apos;ll send you a reset code.</p><div className="mt-8 text-left"><PasswordResetRequestForm /></div><div className="mt-8 flex items-center gap-3 text-sm text-public-muted-text"><span className="h-px flex-1 bg-public-border" /><span>or</span><span className="h-px flex-1 bg-public-border" /></div><Link href="/login" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-public-primary hover:underline"><ArrowLeft className="size-4" aria-hidden="true" />Back to sign in</Link></div></section></div></main>;
}
